apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-producer
  name: java-http-vertx-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-producer
  template:
    metadata:
      labels:
        app: java-http-vertx-producer
    spec:
      containers:
      - name: java-http-vertx-producer
        image: quay.io/strimzi-examples/java-http-vertx-producer:latest
        env:
          - name: STRIMZI_HOSTNAME
            value: my-bridge-bridge-service
          - name: STRIMZI_PORT
            value: "8080"
          - name: STRIMZI_TOPIC
            value: my-topic
          - name: STRIMZI_SEND_INTERVAL
            value: "1000"
          - name: STRIMZI_MESSAGE_COUNT
            value: "1000000"
          - name: STRIMZI_TRACING_SYSTEM
            value: "opentelemetry"
          - name: OTEL_SERVICE_NAME
            value: http-vertx-otel
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://my-otlp-endpoint:4317
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-consumer
  name: java-http-vertx-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-consumer
  template:
    metadata:
      labels:
        app: java-http-vertx-consumer
    spec:
      containers:
      - name: java-http-vertx-consumer
        image: quay.io/strimzi-examples/java-http-vertx-consumer:latest
        env:
          - name: STRIMZI_HOSTNAME
            value: my-bridge-bridge-service
          - name: STRIMZI_PORT
            value: "8080"
          - name: STRIMZI_TOPIC
            value: my-topic
          - name: STRIMZI_GROUPID
            value: "my-group"
          - name: STRIMZI_POLL_INTERVAL
            value: "1000"
          - name: STRIMZI_TRACING_SYSTEM
            value: "opentelemetry"
          - name: OTEL_SERVICE_NAME
            value: http-vertx-otel
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://my-otlp-endpoint:4317
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"