sudo: required
language: java
jdk:
- openjdk11
services:
- docker
script:
- "./.travis/build.sh"
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - COMMIT=${TRAVIS_COMMIT::8}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-main}
  - DOCKER_REGISTRY=quay.io
  - DOCKER_ORG=strimzi-examples
  - secure: EexMgGNssGSj1IkbfcUTqcT8xYJhnjFJWU9T0sInm+u9Tv4NFWLTTWFAwQtCYjlgmue2mYIqeIS1z3fRNBxWTKFFKWRp29YghvtvcPJlKu8KCR8Psshuz0ZrW1ws7Uipx69AT3TSDhzafm1aDH3WDMnqvmJkCPp0y3tTQT27WZ2c4ma8Z3vltJf4BY+rGFBbJZFJtXcNgt1FhI+pFToH53eIiLpWpNXm0emB8eJEBgQDvwG185GcETGJC5yOEKbhdHKZkjFH/4hYlzf9tLgQS8IkvWKnzzTj6hKue7dkMXOInZllqSA1EMr+HrMPS9NE5MKgWyPy+pzLK2HMVictA//4CyFYw6sZFxRFKv83sQcfBY5eHbBJG0t+cXjv42wiXEqOVO89RpNi/l8zSMe5iOafWtIamRRvq86pTYohtkZH37/YMZP/AyTTP4zeiET1fx5Nh41TlQ9sXPdIF+mJcSOIZ249uteVX08MPZKV/A1dK8jDbHEr5qiTzMIJsWBOlU+L6gfCwzLhwNodUifJ/7EbiWBLKtHkjPu3cfRPPrEw1DGWzatDFTQVdMsacLzGW8JTiqg9G+Q4UTzFpWQ4HT9PZfQfHLlrqPzcUVmaRnMoVvM41osz8o11uLoLiIZndZ0KFiNQuX8O6tEHk+bG96llgc+mMB/8t+XiX1DIk4c= # QUAY_USER
  - secure: Jw2YIbAdqB0MBHq7XGgUmBkMvbnKPEAtoLsG35xC7zEiX7kLY5Ogvg+zyk7ral013sDLLAs1H25NxdI8jGokTJ44Tk9RtGL6o3wBoFJbJNnOBG8/+hNZt6Am0InCAKqA+XQiPIGKd2ArBvu1QJvD5WM9fCIA5UDZ+XBA1H+ww1q1MNtDiM0d5te2FWdaWGtdAHPy9Oa5axoQ40lUigqi49fbAc7y4cPFS2knicJ3NCXajpv7bYL6SapgqIxPLJNvCgCu0iDQvOLCHwSyqOak5tsWX21EspdyXUAY6HGb8rgElbM3p8qu+lw2KI0X2ypQXcuj8x7JXF/bdwA10Cieh5ILYOF1d07XyNHeWKIEa4mvoEnCV3Q8bGhYJYccU6aj91VH1cBXOe/vab8hVjLRy7TTJwiX4BajfiGTalBCSWS+A6FA/TM6yZOO/4rUZp+F5AqJSUjQqprIKHAlAhMNAeuxQOTVurSaIad/Xn+hdnLZyFoAFGGPpXrTN2yCcW7ZQmZl3+FryTbWC9IchJt5gFLUAwZrlGg8n6zYMk+jHkBg/qvLF2QQO83er4M2L+mEw60Po8vaj6xCQ78TVqnwgpK/68P4r2WuXBO+I1ECQ1LH5xAxC8M0IwwzEpusdtN6rRRurEGUJdOvCBx/IXpGA30m9TpWQpZPjFoyuvCDAbk= # QUAY_PASS
