apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
      strimzi.io/cluster: my-source-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: cipot-ym
  labels:
    strimzi.io/cluster: my-source-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-target-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: cipot-ym
  labels:
    strimzi.io/cluster: my-target-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world-producer
  name: hello-world-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-producer
    spec:
      containers:
      - name: hello-world-producer
        image: scholzj/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-source-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: JAEGER_SERVICE_NAME
            value: hello-world-producer
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world-consumer
  name: hello-world-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-consumer
    spec:
      containers:
      - name: hello-world-consumer
        image: scholzj/hello-world-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-target-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: my-hello-world-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: JAEGER_SERVICE_NAME
            value: hello-world-consumer
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
---
#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  labels:
#    app: ahoj-svete-consumer
#  name: ahoj-svete-consumer
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: ahoj-svete-consumer
#    spec:
#      containers:
#        - name: ahoj-svete-consumer
#          image: scholzj/hello-world-consumer:latest
#          env:
#            - name: BOOTSTRAP_SERVERS
#              value: my-cluster-target-kafka-bootstrap:9092
#            - name: TOPIC
#              value: my-topic
#            - name: GROUP_ID
#              value: my-ahoj-svete-consumer
#            - name: LOG_LEVEL
#              value: "INFO"
#            - name: MESSAGE_COUNT
#              value: "1000000"
#            - name: JAEGER_SERVICE_NAME
#              value: ahoj-svete-consumer
#            - name: JAEGER_AGENT_HOST
#              value: my-jaeger-agent
#            - name: JAEGER_SAMPLER_TYPE
#              value: const
#            - name: JAEGER_SAMPLER_PARAM
#              value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world-streams
  name: hello-world-streams
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-streams
    spec:
      containers:
        - name: hello-world-streams
          image: scholzj/hello-world-streams:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-source-cluster-kafka-bootstrap:9092
            - name: SOURCE_TOPIC
              value: my-topic
            - name: TARGET_TOPIC
              value: cipot-ym
            - name: LOG_LEVEL
              value: "INFO"
            - name: JAEGER_SERVICE_NAME
              value: hello-world-streams
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: remusnoc-dlrow-olleh
  name: remusnoc-dlrow-olleh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: remusnoc-dlrow-olleh
    spec:
      containers:
        - name: remusnoc-dlrow-olleh
          image: scholzj/hello-world-consumer:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-target-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: cipot-ym
            - name: GROUP_ID
              value: remusnoc-dlrow-olleh-ym
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: JAEGER_SERVICE_NAME
              value: remusnoc-dlrow-olleh
            - name: JAEGER_AGENT_HOST
              value: my-jaeger-agent
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
---