# Makefile.maven contains the shared tasks for building Java applications. This file is
# included into the Makefile files which contain some Java sources which should be build
#

java_build:
	echo "Building JAR file ..."
	mvn $(MVN_ARGS) package

java_clean:
	echo "Cleaning Maven build ..."
	mvn $(MVN_ARGS) clean

spotbugs:
	mvn $(MVN_ARGS) spotbugs:check