apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
      - name: java-kafka-consumer
        image: quay.io/strimzi-examples/java-kafka-consumer:latest
        env:
          - name: STRIMZI_TOPIC
            value: my-topic
          - name: STRIMZI_LOG_LEVEL
            value: "INFO"
          - name: STRIMZI_MESSAGE_COUNT
            value: "1000000"
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: KAFKA_GROUP_ID
            value: my-java-kafka-consumer
          - name: KAFKA_KEY_DESERIALIZER
            value: "org.apache.kafka.common.serialization.StringDeserializer"
          - name: KAFKA_VALUE_DESERIALIZER
            value: "org.apache.kafka.common.serialization.StringDeserializer"
