apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-streams
  name: java-kafka-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-streams
  template:
    metadata:
      labels:
        app: java-kafka-streams
    spec:
      containers:
      - name: java-kafka-streams
        image: quay.io/strimzi-examples/java-kafka-streams:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: APPLICATION_ID
            value: java-kafka-streams
          - name: SOURCE_TOPIC
            value: my-topic
          - name: TARGET_TOPIC
            value: cipot-ym
          - name: LOG_LEVELgit checkout
            value: "INFO"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100