apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-native-producer
  name: kafka-native-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-native-producer
  template:
    metadata:
      labels:
        app: kafka-native-producer
    spec:
      containers:
      - name: kafka-native-producer
        image: strimzi/kafka-native-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: PRODUCER_ACKS
            value: "all"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100
