apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-native-streams
  name: kafka-native-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-native-streams
  template:
    metadata:
      labels:
        app: kafka-native-streams
    spec:
      containers:
      - name: kafka-native-streams
        image: strimzi/kafka-native-streams:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-source-cluster-kafka-bootstrap:9092
          - name: APPLICATION_ID
            value: kafka-native-streams
          - name: SOURCE_TOPIC
            value: my-topic
          - name: TARGET_TOPIC
            value: cipot-ym
          - name: LOG_LEVEL
            value: "INFO"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100