apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-native-consumer
  name: kafka-native-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-native-consumer
  template:
    metadata:
      labels:
        app: kafka-native-consumer
    spec:
      containers:
      - name: kafka-native-consumer
        image: strimzi/kafka-native-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: my-kafka-native-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: ADDITIONAL_CONFIG
            value: |
              max.poll.records=100