jobs:
  - job: 'build_container'
    displayName: 'Build'
    # Strategy for the job
    strategy:
      matrix:
        ${{ each arch in parameters.architectures }}:
          ${{ arch }}:
            arch: ${{ arch }}
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-22.04'
    # Pipeline steps
    steps:
      - template: '../steps/prerequisites/install_docker.yaml'
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the target directory"
      - bash: "make docker_build docker_save"
        env:
          DOCKER_BUILDKIT: 1
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          DOCKER_REGISTRY: "quay.io"
          DOCKER_ORG: "strimzi"
          DOCKER_ARCHITECTURE: $(arch)
        displayName: "Build container - $(arch)"

      # We have to TAR the container archives directory and store it
      - bash: tar -cvpf containers-$(arch).tar *-$(arch).tar.gz
        displayName: "Tar the containers"
      - publish: $(System.DefaultWorkingDirectory)/containers-$(arch).tar
        artifact: Containers-$(arch)
