# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'
# Jobs
jobs:
  - job: 'build_and_test'
    displayName: 'Build & Test'
    # Strategy for the job
    strategy:
      matrix:
        'java-17':
          jdk_version: '17'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: Ubuntu-22.04
    # Variables
    variables:
      MVN_CACHE_FOLDER: $(HOME)/.m2/repository
      MVN_ARGS: '-e -V -B'
    # Pipeline steps
    steps:
      - task: Cache@2
        inputs:
          key: 'maven-cache | $(System.JobName) | **/pom.xml'
          restoreKeys: |
            maven-cache | $(System.JobName)
            maven-cache
          path: $(HOME)/.m2/repository
        displayName: Maven cache
      - template: 'templates/setup_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      - bash: ".azure/scripts/build.sh"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          COMMIT: $(Build.SourceVersion)
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASS: $(DOCKER_PASS)
        displayName: "Build and test"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Unit & Integration tests"
        condition: always()
