apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-consumer
  name: java-http-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-consumer
  template:
    metadata:
      labels:
        app: java-http-consumer
    spec:
      containers:
      - name: java-http-consumer
        image: quay.io/strimzi-examples/java-http-consumer:latest
        env:
          - name: STRIMZI_HOSTNAME
            value: my-bridge-bridge-service
          - name: STRIMZI_PORT
            value: "8080"
          - name: STRIMZI_TOPIC
            value: my-topic
          - name: STRIMZI_CLIENTID
            value: "my-consumer"
          - name: STRIMZI_GROUPID
            value: "my-group"
          - name: STRIMZI_POLL_INTERVAL
            value: "1000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
