name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build & Push images
        run: |
          ../scripts/build.sh
        with:
          DOCKER_USER: ${{ secret.DOCKER_USER }}
          DOCKER_PASS: ${{ secret.DOCKER_PASS }}
